version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_batch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/batch_example/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: batch_example
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432